const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('league', {
  getStatus: () => ipcRenderer.invoke('lcu:status'),
  getProfileIcon: (id) => ipcRenderer.invoke('profile:icon', id),
  getRoles: () => ipcRenderer.invoke('roles:get'),
  saveRoles: (roles) => ipcRenderer.invoke('roles:save', roles),
  launch: () => ipcRenderer.invoke('league:launch'),
  openClient: () => ipcRenderer.invoke('league:open-client'),
  getReadyState: () => ipcRenderer.invoke('ready:state'),
  createRanked: () => ipcRenderer.invoke('lobby:create-ranked'),
  invite: (name) => ipcRenderer.invoke('lobby:invite', name),
  getOnlineFriends: () => ipcRenderer.invoke('friends:online'),
  inviteSummoner: (summonerId, name) => ipcRenderer.invoke('lobby:invite-summoner', summonerId, name),
  kickMember: (summonerId) => ipcRenderer.invoke('lobby:kick-member', summonerId),
  acceptInvitation: (id) => ipcRenderer.invoke('invitation:accept', id),
  listQueues: () => ipcRenderer.invoke('queues:list'),
  selectQueue: (id) => ipcRenderer.invoke('queue:select', id),
  switchArenaTeam: (subteamIndex, position) => ipcRenderer.invoke('arena:team', subteamIndex, position),
  setWidgetSize: (width, height) => ipcRenderer.invoke('widget:size', width, height),
  getChampSelectData: () => ipcRenderer.invoke('cs:data'),
  getAsset: (assetPath) => ipcRenderer.invoke('asset:image', assetPath),
  champHover: (championId) => ipcRenderer.invoke('cs:hover', championId),
  champLock: () => ipcRenderer.invoke('cs:lock'),
  setSpells: (spell1Id, spell2Id) => ipcRenderer.invoke('cs:spells', spell1Id, spell2Id),
  answerSwap: (kind, id, accept) => ipcRenderer.invoke('cs:swap', kind, id, accept),
  reroll: () => ipcRenderer.invoke('cs:reroll'),
  benchSwap: (championId) => ipcRenderer.invoke('cs:bench', championId),
  getRunes: () => ipcRenderer.invoke('runes:data'),
  selectRunePage: (id) => ipcRenderer.invoke('runes:select', id),
  saveRunePage: (page, target) => ipcRenderer.invoke('runes:save', page, target),
  declineInvitation: (id) => ipcRenderer.invoke('invitation:decline', id),
  startSearch: () => ipcRenderer.invoke('lobby:start-search'),
  cancelSearch: () => ipcRenderer.invoke('lobby:cancel-search'),
  acceptReady: () => ipcRenderer.invoke('ready:accept'),
  hideReady: () => ipcRenderer.invoke('window:hide-ready'),
  closeWidget: () => ipcRenderer.invoke('widget:close'),
  onReadyCheck: (callback) => ipcRenderer.on('ready-check', (_event, state) => callback(state))
});
